- name: Check Nodejs
  ansible.builtin.shell: type node
  ignore_errors: yes
  register: node_stat

- name: Disable NodeJs default version
  ansible.builtin.shell: dnf module disable nodejs -y
  when: node_stat != 0

- name: Enable NodeJs 18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y
  when: node_stat != 0

- name: Installing NodeJs
  ansible.builtin.dnf:
    name: nodejs
    state: present
  when: node_stat != 0

- name: Import common role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Download NodeJs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: "{{app_dir}}"        #It will go to /app directory and do npm install

- name: Install New Relic NodeJS Library
  ansible.builtin.shell: npm install newrelic --save
  args:
    chdir: "{{app_dir}}"

- name: Import SystemD
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

- name: Import Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: schema-load
  when : schema_needed

- name: Import Observability
  ansible.builtin.import_role:
    name: common
    tasks_from: observability


